site_name: Low-Ops Platform
site_url: https://docs.low-ops.com/
theme:
  name: 'material'
  logo: assets/logo.png
  custom_dir: overrides
  palette:
    primary: 'blue'
    accent: 'blue gray'
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - header.autohide
extra:
  homepage: https://low-ops.com/
  version:
    provider: mike
plugins:
  - search
copyright: Copyright &copy; 2022 - 2024 CINAQ.com